{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: 111结果不相等3\nassert '111' == 3", "trace": "self = <auto_test.test_demo.Test01 object at 0x00000243A001F5B0>, front = '111'\n\n    @allure.feature(\"测试二\")\n    def test_02 (self, front) :\n>       assert front == 3, f\"{front}结果不相等3\"\nE       AssertionError: 111结果不相等3\nE       assert '111' == 3\n\nauto_test\\test_demo.py:26: AssertionError"}, "start": 1639067315640, "stop": 1639067315640, "uuid": "806e5656-60e0-44b4-9c15-0036b07a8f84", "historyId": "e68cbc71aaf9a375c0c964e493eca539", "testCaseId": "494b411950329e111005d64bbb494189", "fullName": "auto_test.test_demo.Test01#test_02", "labels": [{"name": "feature", "value": "测试二"}, {"name": "parentSuite", "value": "auto_test"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "Test01"}, {"name": "host", "value": "DSCCT2021"}, {"name": "thread", "value": "30824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "auto_test.test_demo"}]}